### PR TITLE
Fixed sending post logic

### LINKED ISSUE #111: Comments after the demo
- [x] Change avatar on header
- [x] Change title for profile page if user on his own page
- [x] Add reset button on search page
- [x] Disable buttons for user card on settings & register pages
- [x] Adding post on a page without reloading

#111

### PR DESCRIPTION
**Pull request by OrestHaponov**
If user send post to another user, it appears without reloading page.

### CODE REVIEW

File: frontend/src/services/postService.ts [hunk 1]
```diff
@@ -2,4 +2,4 @@ import { dataType } from '../components/interfaces/Interface';
 import { getRequest, postRequest } from './apiService';
 
 export const getUserPosts = (id?: string) => getRequest(`${dataType.user}/${id}/${dataType.posts}`);
-export const sendPostToUser = (id: string, body: {}) => postRequest(`${dataType.user}/${id}/${dataType.posts}`, body);
+export const sendPostToUser = (id: string, body: {}) => postRequest(`${dataType.user}/${id}/${dataType.posts}`, body).then(res => res);
```
Comment (oleksandrstarov) [inline frontend/src/services/postService.ts]: What the point of doing this?

Comment (OrestHaponov) [reply frontend/src/services/postService.ts]: I removed it. This part(.then(res => res))

**Review by grok-rs — APPROVED** [review]
