### PR TITLE
changed routes, increased chunk limit

### LINKED ISSUE #133: Create user in friends' collection after "Sign Up"

### LINKED ISSUE #135: Uncaught TypeError: Cannot read property '_id' of null
There is an issue on staging environment
once navigated to app there is an error in console:

Steps to reproduce:
1. go to http://nodejs-mongo-persistent-js-internship-2020.e4ff.pro-eu-west-1.openshiftapps.com/
2. check console output
3. check application screen

expected result: No errors in console, application renders login

actual result: Error in console, nothing on the screen

Uncaught TypeError: Cannot read property '_id' of null

We have the Profile component on '/' path (why?), and once we try to load user from LS it is null since we are not authorised - and we are not able to read _id of null (userDetails) in useEffect hook.
HAVE TO REDIRECT TO /login path in this case (user is null)

Questions:
1. Why we going to / and render profile in this case? 
2. Need to add check for empty LS to avoid error 

Note - same for /login path due to 
` getFriends(user._id)....` in friendsContext (user is null from LS)

### PR DESCRIPTION
**Pull request by grok-rs**
### Changes

- Add userId to friends collection after register
- changed routes, if user exists than move him to profile.
- transferred friendsProvider to another component, because, if we opened register, login it would called itself.
- increased limit for requests ( when you were registering, component could throw an error) 
- added check for posts 
p.s, @Pr1sm0 will add middleware, and if user didn't exist it would transfer him to login

### CODE REVIEW

File: backend/src/data/repository/user.ts [hunk 1]
```diff
@@ -17,7 +17,8 @@ export class UserRepository {
   async createUser(newUser: DTO.IUser): Promise<DTO.IUserDoc> {
     const user = new User(newUser);
     const res = await user.save();
-    return res._id;
+    const friend = await UserRepository.addUserIdToFriends(res._id);
```
Comment (apastuhov) [inline backend/src/data/repository/user.ts]: why user is added to friends right after his creation? It should be done by a separate route, no?

File: frontend/src/components/pages/login/Login.tsx [hunk 2]
```diff
@@ -8,18 +8,29 @@ import { processGoogleResponse } from '../../../services/sessionService';
...
     }
   };
+
+  useEffect(() => {
+    try {
+      const user = getUserFromStorage();
+      if (user._id) {
+        history.push(`/user/${user._id}`);
+      }
+    } catch (e) {}
```
Comment (oleksandrstarov) [inline frontend/src/components/pages/login/Login.tsx]: at least use alert with "something went wrong" in catch

File: frontend/src/components/pages/profile/Profile.tsx [hunk 3]
```diff
@@ -23,11 +23,11 @@ const Profile: React.FC<IParamsProps> = props => {
...
   const location = useLocation();
   const userId = props.match.params.id;
-  const { _id } = getUserFromStorage();
+  const myInfo = getUserFromStorage();
 
   useEffect(() => {
-    if (!userId) {
-      const user = getUserFromStorage();
+    const user = getUserFromStorage();
+    if (userId === user._id) {
```
Comment (oleksandrstarov) [inline frontend/src/components/pages/profile/Profile.tsx]: user?._id to be null safe check

File: frontend/src/components/pages/profile/Profile.tsx [hunk 4]
```diff
@@ -40,24 +40,19 @@ const Profile: React.FC<IParamsProps> = props => {
...
-            <div className="leftside">
-              <UserCard mainInfo={userDetails} boxShadow={2} isProfile />
-              <About about={userDetails.about} />
-              <FriendsList id={userDetails._id} friends={friends} />
-            </div>
-            <div className="rightside">
-              <AddPostForm _id={userDetails._id} />
-              <Posts posts={userPosts} />
-            </div>
+      <Layout pageTitle={`${userDetails._id === myInfo?._id ? 'My' : ''} Profile`}>
```
Comment (apastuhov) [inline frontend/src/components/pages/profile/Profile.tsx]: better to create `isCurrentUser` method in `sessionStorageService `, so it can be reused in multiple places

File: frontend/src/components/pages/profile/components/posts/Posts.tsx [hunk 5]
```diff
@@ -9,8 +9,12 @@ import './posts.scss';
 
 const Posts: React.FC<IPostsProps> = ({ posts }) => {
   const sortedPosts = useMemo(() => {
-    const newPosts = [...posts].reverse();
-    return newPosts;
+    if (posts.length === 0) {
+      return [];
```
Comment (oleksandrstarov) [inline frontend/src/components/pages/profile/components/posts/Posts.tsx]: for empty array no need to do this check - can be return [...posts].reverse();

**Review by oleksandrstarov — CHANGES_REQUESTED** [review]

**Review by apastuhov — APPROVED** [review]

**Review by apastuhov — DISMISSED** [review]
Fix comments please

File: backend/src/data/repository/user.ts (hunk 1 above)
Comment (grok-rs) [reply backend/src/data/repository/user.ts]: It just initialize of user, after creation we put record with userId and empty array of friends to collection friends. I'm not sure, that we should return user and create record in collection by using another service, it need for looking for userId in friends collection and put a new id of friend to array

**Review by oleksandrstarov — APPROVED** [review]
