### PR TITLE
Refactor chat's front end, set id's types as a string, fix routing, delete redundant syntax

### LINKED ISSUE #103: Initialize frontend search by user name on chat page.
#103

### LINKED ISSUE #123: Front end for chat page
Front end refactoring for integration with backend

### PR DESCRIPTION
**Pull request by Pr1sm0**

### CODE REVIEW

File: frontend/src/components/pages/chat/components/chatList/ChatList.tsx [hunk 1]
```diff
@@ -28,26 +18,38 @@ export const ChatList: React.FC = () => {
   };
 
   useEffect(() => {
+    const getChats = async () => {
+      setIsLoading(true);
+      const user = await getUserFromStorage();
+      const dialogs = await getAllDialogs(user._id);
+      const newDialogs = dialogs.map(
+        (dialog: any): DialogInfoProps => {
```
Comment (oleksandrstarov) [inline frontend/src/components/pages/chat/components/chatList/ChatList.tsx]: Don`t we have a type for Dialog?

File: frontend/src/components/pages/chat/components/chatList/ChatList.tsx [hunk 2]
```diff
@@ -28,26 +18,38 @@ export const ChatList: React.FC = () => {
...
+              date: dayjs(dialog.messages[0].date).format('DD.MM.YY')
+            };
+          }
+          return {
+            dialogId: dialog._id,
+            photo: dialog.participants[0].avatar,
+            name: `${dialog.participants[0].firstName} ${dialog.participants[0].lastName}`,
+            text: dialog.messages[0].body,
+            date: dayjs(dialog.messages[0].date).format('DD.MM.YY')
+          };
```
Comment (oleksandrstarov) [inline frontend/src/components/pages/chat/components/chatList/ChatList.tsx]:
```
const {avatar, firstName, lastName } = dialog.participants.find(({ _id })= > _id !== user._id) || {};
return {
            dialogId: dialog._id,
            photo: avatar,
            name: `${firstName} ${lastName}`,
            text: dialog.messages[0].body,
            date: dayjs(dialog.messages[0].date).format('DD.MM.YY')
          };
```

File: frontend/src/components/pages/chat/components/chatList/ChatList.tsx [hunk 3]
```diff
@@ -28,26 +18,38 @@ export const ChatList: React.FC = () => {
...
+        }
+      );
+      const results = newDialogs.filter((chat: DialogInfoProps) =>
+        chat.name.toLowerCase().includes(search.toLowerCase())
+      );
+      setSearchResults(results);
+      setIsLoading(false);
```
Comment (oleksandrstarov) [inline frontend/src/components/pages/chat/components/chatList/ChatList.tsx]: since we newer use search on BE no any reason to fetch new dialogs on search. Should be separate useEffect for filtering only

File: frontend/src/components/pages/chat/components/chatListItem/ChatListItem.tsx [hunk 4]
```diff
@@ -4,27 +4,32 @@ import { Link } from 'react-router-dom';
...
-
+export const ChatListItem: React.FC<DialogInfoProps> = ({ dialogId, photo, name, text, date }) => {
+  const [currentDialogId, setCurrentDialogId] = useState('');
   const [isActive, setIsActive] = useState<boolean>(false);
   // id = id current set is active true
   const toggleChat = () => {
-    setIsActive(!isActive);
+    if (currentDialogId === dialogId) {
+      setIsActive(true);
+    }
```
Comment (oleksandrstarov) [inline frontend/src/components/pages/chat/components/chatListItem/ChatListItem.tsx]: Not sure this will toggle dialog actually

File: frontend/src/components/pages/chat/components/compose/Compose.tsx [hunk 5]
```diff
@@ -1,11 +1,39 @@
...
+import React, { useState } from 'react';
+import { useParams } from 'react-router-dom';
+import { createMessage } from '../../../../../services/apiChatService';
+import { getUserFromStorage } from '../../../../../services/sessionStorageService';
 import './compose.scss';
 
 export const Compose: React.FC = () => {
+  const [messageValue, setMessageValue] = useState<string>('');
+  const [loginedUser] = useState(getUserFromStorage());
+  const { dialogId } = useParams<any>();
```
Comment (oleksandrstarov) [inline frontend/src/components/pages/chat/components/compose/Compose.tsx]: please set a type for this

File: frontend/src/components/pages/chat/components/messageList/MessageList.tsx [hunk 6]
```diff
@@ -1,52 +1,87 @@
...
 
-const MY_USER_ID = 'apple';
-
 export const MessageList: React.FC = () => {
-  const [messages, setMessages] = useState<Array<any>>([]);
+  const [messages, setMessages] = useState<Array<DTO.IMessage>>([]);
+  const [userId, setUserId] = useState('');
+  const [userName, setUserName] = useState('');
   const { dialogId } = useParams<any>();
+  const chatUserId = getUserFromStorage()._id;
```
Comment (oleksandrstarov) [inline frontend/src/components/pages/chat/components/messageList/MessageList.tsx]: it is better to use same style for variables returned by function, compare lines 16 and 17

File: frontend/src/components/pages/chat/components/messageList/MessageList.tsx [hunk 7]
```diff
@@ -1,52 +1,87 @@
...
     setMessages([]);
     (async () => {
       const messages = await getChatMessages(dialogId);
-      setMessages(messages);
+      setMessages(messages.messages);
+      if (chatUserId !== messages.participants[1]) {
+        setUserId(messages.participants[1]);
+      } else {
+        setUserId(messages.participants[0]);
+      }
```
Comment (oleksandrstarov) [inline frontend/src/components/pages/chat/components/messageList/MessageList.tsx]:
```
const chatPaticipant = messages.participants.find((id) => chatUserId !== chatUserId);
setUserId(chatPaticipant);
```

**Review by oleksandrstarov — CHANGES_REQUESTED** [review]

**Review by oleksandrstarov — APPROVED** [review]
LGTM
